- name: temp
  hosts: localhost
  vars:
    list:
      - { name: test1, content: test1content }
      - { name: test2, content: test2content }
  tasks:

    - name: temp
      copy: 
        content: "{{ item.content }}"
        dest: "~/{{ item.name }}"
        force: no
      loop: "{{ list }}"
      


