- name: include iteration vars
  include_vars:
    file: "{{ item }}"
  with_items: "{{ thing.import_files }}"

- name: role task
  copy: 
    content: "{{ testvar }}, {{ testvaranother }}"
    dest: ~/{{ thing.name }}
    force: no

