- name: temp
  hosts: localhost
  vars:
    list:
      - test1
      - test2
      - test3

  tasks:
    - name: temp
      template: 
        src: template.yml
        dest: /home/sinfiej/temp/template.yml

